version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.05.0-ce
      - checkout
      - run:
          name: run tests
          command: docker --version

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: gggg
          command: echo Testststs

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          type: approval
