version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker:
#          docker_layer_caching: true
          version: 17.05.0-ce
      - checkout
      - run:
          name: run tests
          command: docker --version

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
        user: root
    steps:
      - run:
          name: gggg
          command: echo Testststs
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose ls

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
#          type: approval
